<span style = "font-size:20px"> **(1) Create a one dimensinoal array that contains numbers from 1 to 10.**</span><br>
    **Use `np.array()`**

In [11]:
import numpy as np
array1=np.array([i for i in range(1,11)])
print(array1)

[ 1  2  3  4  5  6  7  8  9 10]


<span style = "font-size:20px"> **(2) Create the following arrays** </span><br>
[[15, 12, 9, 22],<br>
 [21, 7, 10, 14],<br>
 [31, 10, 33, 8]]<br>
 **Use `np.array()`**

In [2]:
import numpy as np
array1=np.array([[15, 12, 9, 22],
                 [21, 7, 10, 14],
                 [31, 10, 33, 8]])
print (array1)

[[15 12  9 22]
 [21  7 10 14]
 [31 10 33  8]]


<span style = "font-size:20px"> **(3) Create an array full of zeros and of shape (2,3).**</span><br>
    **Use `np.zeros()`**

In [22]:
import numpy as np
array1=np.zeros((2,3))
print(array1.astype(int))

[[0 0 0]
 [0 0 0]]


<span style = "font-size:20px"> **(4) Create an array that contains odd numbers from 1 to 1000.**</span><br>
**Use: `np.arange()`**

In [6]:
import numpy as np
array1=np.arange(1,1000,2)
print (array1)

[  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107
 109 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143
 145 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179
 181 183 185 187 189 191 193 195 197 199 201 203 205 207 209 211 213 215
 217 219 221 223 225 227 229 231 233 235 237 239 241 243 245 247 249 251
 253 255 257 259 261 263 265 267 269 271 273 275 277 279 281 283 285 287
 289 291 293 295 297 299 301 303 305 307 309 311 313 315 317 319 321 323
 325 327 329 331 333 335 337 339 341 343 345 347 349 351 353 355 357 359
 361 363 365 367 369 371 373 375 377 379 381 383 385 387 389 391 393 395
 397 399 401 403 405 407 409 411 413 415 417 419 421 423 425 427 429 431
 433 435 437 439 441 443 445 447 449 451 453 455 457 459 461 463 465 467
 469 471 473 475 477 479 481 483 485 487 489 491 49

<span style = "font-size:20px"> **(6) Show what `ndim` do.**</span><br>

In [8]:
#ndim shows the dimensions of the array
import numpy as np
array1=np.zeros(6)
print(array1.ndim)
print(array1)
array1=array1.reshape(2,3)
print(array1.ndim)
print(array1)
array1=array1.reshape(2,3,1)
print(array1.ndim)
print(array1)

1
[0. 0. 0. 0. 0. 0.]
2
[[0. 0. 0.]
 [0. 0. 0.]]
3
[[[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]]


<span style = "font-size:20px"> **(7) What is the difference between `shape` and `size`?**</span><br>
**Explain with words and with `code`.**

In [9]:
#Shape returns a tuple containing the length of each dimension ,size returns an integer repersenting the number of values
import numpy as np
array1=np.ones(6)
array1=array1.reshape(2,3,1)
print(array1)
print(array1.shape)
print(array1.size)

[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]]
(2, 3, 1)
6


<span style = "font-size:20px"> **(8) Flat the following array.**</span><br>

In [15]:
arr = np.array([[i, 2*i, 3*i] for i in range(3, 300)])
arr=arr.ravel()    #or arr.reshape(-1)
print(arr)

[  3   6   9   4   8  12   5  10  15   6  12  18   7  14  21   8  16  24
   9  18  27  10  20  30  11  22  33  12  24  36  13  26  39  14  28  42
  15  30  45  16  32  48  17  34  51  18  36  54  19  38  57  20  40  60
  21  42  63  22  44  66  23  46  69  24  48  72  25  50  75  26  52  78
  27  54  81  28  56  84  29  58  87  30  60  90  31  62  93  32  64  96
  33  66  99  34  68 102  35  70 105  36  72 108  37  74 111  38  76 114
  39  78 117  40  80 120  41  82 123  42  84 126  43  86 129  44  88 132
  45  90 135  46  92 138  47  94 141  48  96 144  49  98 147  50 100 150
  51 102 153  52 104 156  53 106 159  54 108 162  55 110 165  56 112 168
  57 114 171  58 116 174  59 118 177  60 120 180  61 122 183  62 124 186
  63 126 189  64 128 192  65 130 195  66 132 198  67 134 201  68 136 204
  69 138 207  70 140 210  71 142 213  72 144 216  73 146 219  74 148 222
  75 150 225  76 152 228  77 154 231  78 156 234  79 158 237  80 160 240
  81 162 243  82 164 246  83 166 249  84 168 252  8

<span style = "font-size:20px"> **(9) Transpose the following array.**</span><br>

In [16]:
arr = np.array([[[[j, j + 1] for j in range(5)]] for i in range(3)])
arr=arr.transpose()
print(arr)

[[[[0 0 0]]

  [[1 1 1]]

  [[2 2 2]]

  [[3 3 3]]

  [[4 4 4]]]


 [[[1 1 1]]

  [[2 2 2]]

  [[3 3 3]]

  [[4 4 4]]

  [[5 5 5]]]]


<span style = "font-size:20px"> **(10) How many unique values are in the following array and print them.**</span><br>

In [20]:
countries = np.array(['canada','spain','india','usa','canada','england','japan','germany','india','england','egypt','england','japan','egypt','india','japan'
                     ,'china','germany','india','china','canada','india','canada''egypt','china','germany','japan','russia'
                    ,'england','usa','germany','china','russia''germany''china','spain''spain','canada','germany','spain',
                    'china','canada','china''canada','germany','russia','japan','india','russia','egypt', 'canada',
                    'spain','india','usa','canada','england','japan','germany','india','england','egypt','england','japan',
                    'egypt','india','japan','china','germany','india','china','canada','india','canada''egypt','china','germany','japan','russia'
                      ,'england','usa','germany','china','russia''germany''china','spain''spain','canada','germany','spain',
                      'china','canada','china''canada','germany','russia','japan','india','russia','egypt'])
arr= np.unique(countries)
unique_list=[]
for x in arr :
    if len(x)<=7 :
     unique_list.append(x)
unique_arr=np.array(unique_list)
print(unique_arr.size,unique_arr)

10 ['canada' 'china' 'egypt' 'england' 'germany' 'india' 'japan' 'russia'
 'spain' 'usa']


(11) Given the following arrays:

```python
import numpy as np

A = np.arange(1, 13).reshape(3, 4)
B = np.array([10, 20, 30])

### 1. Shapes
What is the shape of:
- `A[1]`  
- `B`

---

### 2. Broadcasting Issue
Why does the following operation fail?

```python
result = A[1] * B



### Question : The Embedding Challenge
You are given two arrays:
1. `array_a`: A 5x5 grid filled with the number `9`.
2. `array_b`: A 3x3 grid filled with the number `1`.

**Task:** Use slicing to "embed" `array_b` into the center of `array_a`. Do **not** use loops.

**Expected Result:**
```python
[[9, 9, 9, 9, 9],
 [9, 1, 1, 1, 9],
 [9, 1, 1, 1, 9],
 [9, 1, 1, 1, 9],
 [9, 9, 9, 9, 9]]

In [23]:
array_a = np.full((5, 5), 9)
array_b = np.ones((3, 3))

array_a[1:4,1:4]=array_b


print(array_a)

[[9 9 9 9 9]
 [9 1 1 1 9]
 [9 1 1 1 9]
 [9 1 1 1 9]
 [9 9 9 9 9]]


##  NumPy Dimensions – Questions

1. What is the shape of `a` and `b`?  

2. What does `(3,)` mean in NumPy? Why is there a comma?  

3. How many dimensions does each array have?  

4. What does each dimension (axis) represent in `b`?  

5. Is `(3,)` the same as `(3, 1)`? Explain the difference.  

In [34]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a.shape,b.shape)
#it means a one dimensional array with 3 elements. shape attribute returns a tuple so the coma is used to diffrentiate between tuples and normal parentheses
print(f"A :{a.ndim}, B :{b.ndim}")
#axis 0 (vertical) reperesent the rows and axis 1 (horizontal) reperesent the columns
#no, (3,) means a single-row-flat array with 3 values, while (3,1) means a cloumn with 3 value in meaning it is not a flat array

(3,) (3, 2)
A :1, B :2
